import { FC } from 'react'
import styles from './PagesLoader.module.css'
import ContentLoader from 'react-content-loader'
import { isMobile } from '@/utils'

interface PagesLoaderProps {
  component?: string
}

const PagesLoader: FC<PagesLoaderProps> = ({component}) => {
  const isMob = isMobile()
  return (
    <div className={styles.wrapper}>
      {component === 'store' ? (
        <>
          {!isMob ? (
            <>
              <ContentLoader
                speed={2}
                width="100%"
                backgroundColor="#f3f3f3"
                foregroundColor="#ecebeb"
                height={256}
              >
                <rect x="0" y="0" width="160" height="157" fill="#D9DBE9" />
                <rect
                  x="172"
                  y="15"
                  width="126"
                  height="8.75"
                  rx="4.375"
                  fill="#D9DBE9"
                />
                <rect
                  x="172"
                  y="27.75"
                  width="126"
                  height="8.75"
                  rx="4.375"
                  fill="#D9DBE9"
                />
                <rect
                  x="173"
                  y="55.5"
                  width="14"
                  height="14"
                  rx="7"
                  fill="#D9DBE9"
                />
                <rect
                  x="192"
                  y="57.5"
                  width="86"
                  height="10.5"
                  rx="5.25"
                  fill="#D9DBE9"
                />
                <rect
                  x="172"
                  y="90.5"
                  width="58"
                  height="15.75"
                  rx="7.875"
                  fill="#D9DBE9"
                />
                <rect
                  x="173"
                  y="134.5"
                  width="130"
                  height="22"
                  rx="7"
                  stroke="#D9DBE9"
                  stroke-width="2"
                />
                <rect
                  x="13.6699"
                  y="168.191"
                  width="108"
                  height="15.6458"
                  rx="7.82288"
                  fill="#D9DBE9"
                />
                <rect
                  x="13.6699"
                  y="199.482"
                  width="259"
                  height="11.7343"
                  rx="5.86716"
                  fill="#D9DBE9"
                />
              </ContentLoader>
            </>
          ) : (
            <ContentLoader
              speed={2}
              width="100%"
              height="265"
              backgroundColor="#f3f3f3"
                foregroundColor="#ecebeb"
              viewBox="0 0 313 auto"
            >
              <rect x="0" y="0" width="160" height="160" fill="#D9DBE9" />
              <rect
                x="170"
                y="5.66%"
                width="50%"
                height="3.3%"
                rx="4.375"
                fill="#D9DBE9"
              />
              <rect
                x="170"
                y="10.47%"
                width="50%"
                height="3.3%"
                rx="4.375"
                fill="#D9DBE9"
              />
              <rect
                x="170"
                y="20.94%"
                width="17"
                height="17"
                rx="9"
                fill="#D9DBE9"
              />
              <rect
                x="200"
                y="22.1%"
                width="41%"
                height="3.96%"
                rx="5.25"
                fill="#D9DBE9"
              />
              <rect
                x="170"
                y="34.15%"
                width="20%"
                height="5.94%"
                rx="7.875"
                fill="#D9DBE9"
              />
              <rect
                x="170"
                y="50.75%"
                width="50%"
                height="8.3%"
                rx="7"
                stroke="#D9DBE9"
                stroke-width="2"
              />
              <rect
                x="10"
                y="63.5%"
                width="34.39%"
                height="5.9%"
                rx="7.82288"
                fill="#D9DBE9"
              />
              <rect
                x="10"
                y="75.3%"
                width="82.49%"
                height="4.43%"
                rx="5.86716"
                fill="#D9DBE9"
              />
            </ContentLoader>
          )}
        </>
      ) : (
        <>
          {!isMob ? (
            <>
              <div className={styles.box}></div>
              <ContentLoader
                speed={2}
                width="100%"
                backgroundColor="#f3f3f3"
                foregroundColor="#ecebeb"
                height={130}
              >
                <svg
                  width="314"
                  height="265"
                  viewBox="0 0 314 265"
                  fill="none"
                  xmlns="http://www.w3.org/2000/svg"
                >
                  <rect
                    x="1.16992"
                    y="0.5"
                    width="312"
                    height="264"
                    rx="7.5"
                    fill="white"
                    stroke="#EBEDF0"
                  />
                </svg>

                <rect
                  x="10"
                  y="10"
                  width="48"
                  height="48"
                  rx={6}
                  ry={6}
                  fill="#F7F5F9"
                />
                <rect
                  x="69"
                  y="12"
                  width="230"
                  height="14"
                  rx={6}
                  ry={6}
                  fill="#F7F5F9"
                />
                <rect
                  x="69"
                  y="40"
                  width="97"
                  height="14"
                  rx={6}
                  ry={6}
                  fill="#F7F5F9"
                />

                <rect
                  x="10"
                  y="64"
                  width="204"
                  height="14"
                  rx={6}
                  ry={6}
                  fill="#F7F5F9"
                />
                <rect
                  x="10"
                  y="85"
                  width="204"
                  height="14"
                  rx={6}
                  ry={6}
                  fill="#F7F5F9"
                />
                <rect
                  x="10"
                  y="106"
                  width="204"
                  height="14"
                  rx={6}
                  ry={6}
                  fill="#F7F5F9"
                />
              </ContentLoader>
            </>
          ) : (
            <ContentLoader
              speed={2}
              width="100%"
              height="288"
              viewBox="0 0 360 auto"
              backgroundColor="#f3f3f3"
                foregroundColor="#ecebeb"
            >
              <rect
                x="0.5"
                y="0.5"
                width="100%"
                height="42%"
                fill="#F7F5F9"
                stroke="#F7F5F9"
              />
              <rect
                x="10"
                y="45%"
                width="48"
                height="48"
                rx="3.5"
                fill="#F7F5F9"
                stroke="#D9DBE9"
              />

              <rect
                x="70"
                y="53%"
                width="10"
                height="14"
                rx="5"
                fill="#D9DBE9"
              />
              <rect
                x="85"
                y="53%"
                width="21%"
                height="4%"
                rx="5"
                fill="#D9DBE9"
              />
              <rect
                x="70"
                y="45%"
                width="48%"
                height="4%"
                rx="5"
                fill="#D9DBE9"
              />

              <rect
                x="10"
                y="66%"
                width="17"
                height="17"
                rx="8"
                fill="#D9DBE9"
              />
              <rect
                x="37"
                y="66%"
                width="32%"
                height="4%"
                rx="5"
                fill="#D9DBE9"
              />

              <rect
                x="10"
                y="78%"
                width="17"
                height="17"
                rx="8"
                fill="#D9DBE9"
              />

              <rect
                x="15"
                y="89%"
                width="15"
                height="17"
                rx="8"
                fill="#D9DBE9"
              />
              <rect
                x="42"
                y="89%"
                width="15%"
                height="7%"
                rx="8"
                fill="#f7f5f9"
              />
              <rect
                x="130"
                y="89%"
                width="13%"
                height="7%"
                rx="8"
                fill="#f7f5f9"
              />
            </ContentLoader>
          )}
        </>
      )}
    </div>
  )
}

export default PagesLoader
