export type CountryType = {
    name: string;
    currency: string;
    phonePrefix: string;
    currencySymbol: string;
  }
  
 export const countryData: CountryType[] = [
    { name: 'Afghanistan', currency: 'AFN', phonePrefix: '+93', currencySymbol: '؋' },
    { name: 'Albania', currency: 'ALL', phonePrefix: '+355', currencySymbol: 'L' },
    { name: 'Algeria', currency: 'DZD', phonePrefix: '+213', currencySymbol: 'د.ج' },
    { name: 'Andorra', currency: 'EUR', phonePrefix: '+376', currencySymbol: '€' },
    { name: 'Angola', currency: 'AOA', phonePrefix: '+244', currencySymbol: 'Kz' },
    { name: 'Antigua & Deps', currency: 'XCD', phonePrefix: '+1', currencySymbol: '$' },
    { name: 'Argentina', currency: 'ARS', phonePrefix: '+54', currencySymbol: '$' },
    { name: 'Armenia', currency: 'AMD', phonePrefix: '+374', currencySymbol: '֏' },
    { name: 'Australia', currency: 'AUD', phonePrefix: '+61', currencySymbol: '$' },
    { name: 'Austria', currency: 'EUR', phonePrefix: '+43', currencySymbol: '€' },
    { name: 'Azerbaijan', currency: 'AZN', phonePrefix: '+994', currencySymbol: '₼' },
    { name: 'Bahamas', currency: 'BSD', phonePrefix: '+1', currencySymbol: '$' },
    { name: 'Bahrain', currency: 'BHD', phonePrefix: '+973', currencySymbol: 'BD' },
    { name: 'Bangladesh', currency: 'BDT', phonePrefix: '+880', currencySymbol: '৳' },
    { name: 'Barbados', currency: 'BBD', phonePrefix: '+1', currencySymbol: '$' },
    { name: 'Belarus', currency: 'BYN', phonePrefix: '+375', currencySymbol: 'Br' },
    { name: 'Belgium', currency: 'EUR', phonePrefix: '+32', currencySymbol: '€' },
    { name: 'Belize', currency: 'BZD', phonePrefix: '+501', currencySymbol: 'BZ$' },
    { name: 'Benin', currency: 'XOF', phonePrefix: '+229', currencySymbol: 'CFA' },
    { name: 'Bhutan', currency: 'BTN', phonePrefix: '+975', currencySymbol: 'Nu.' },
    { name: 'Bolivia', currency: 'BOB', phonePrefix: '+591', currencySymbol: 'Bs' },
    { name: 'Bosnia Herzegovina', currency: 'BAM', phonePrefix: '+387', currencySymbol: 'KM' },
    { name: 'Botswana', currency: 'BWP', phonePrefix: '+267', currencySymbol: 'P' },
    { name: 'Brazil', currency: 'BRL', phonePrefix: '+55', currencySymbol: 'R$' },
    { name: 'Brunei', currency: 'BND', phonePrefix: '+673', currencySymbol: '$' },
    { name: 'Bulgaria', currency: 'BGN', phonePrefix: '+359', currencySymbol: 'лв' },
    { name: 'Burkina', currency: 'XOF', phonePrefix: '+226', currencySymbol: 'CFA' },
    { name: 'Burundi', currency: 'BIF', phonePrefix: '+257', currencySymbol: 'FBu' },
    { name: 'Cambodia', currency: 'KHR', phonePrefix: '+855', currencySymbol: '៛' },
    { name: 'Cameroon', currency: 'XAF', phonePrefix: '+237', currencySymbol: 'FCFA' },
    { name: 'Canada', currency: 'CAD', phonePrefix: '+1', currencySymbol: '$' },
    { name: 'Cape Verde', currency: 'CVE', phonePrefix: '+238', currencySymbol: '$' },
    { name: 'Central African Rep', currency: 'XAF', phonePrefix: '+236', currencySymbol: 'FCFA' },
    { name: 'Chad', currency: 'XAF', phonePrefix: '+235', currencySymbol: 'FCFA' },
    { name: 'Chile', currency: 'CLP', phonePrefix: '+56', currencySymbol: '$' },
    { name: 'China', currency: 'CNY', phonePrefix: '+86', currencySymbol: '¥' },
    { name: 'Colombia', currency: 'COP', phonePrefix: '+57', currencySymbol: '$' },
    { name: 'Comoros', currency: 'KMF', phonePrefix: '+269', currencySymbol: 'CF' },
    { name: 'Congo', currency: 'XAF', phonePrefix: '+242', currencySymbol: 'FCFA' },
    { name: 'Congo {Democratic Rep}', currency: 'CDF', phonePrefix: '+243', currencySymbol: 'FC' },
    { name: 'Costa Rica', currency: 'CRC', phonePrefix: '+506', currencySymbol: '₡' },
    { name: 'Croatia', currency: 'HRK', phonePrefix: '+385', currencySymbol: 'kn' },
    { name: 'Cuba', currency: 'CUP', phonePrefix: '+53', currencySymbol: '₱' },
    { name: 'Cyprus', currency: 'EUR', phonePrefix: '+357', currencySymbol: '€' },
    { name: 'Czech Republic', currency: 'CZK', phonePrefix: '+420', currencySymbol: 'Kč' },
    { name: 'Denmark', currency: 'DKK', phonePrefix: '+45', currencySymbol: 'kr' },
    { name: 'Djibouti', currency: 'DJF', phonePrefix: '+253', currencySymbol: 'Fdj' },
    { name: 'Dominica', currency: 'XCD', phonePrefix: '+1', currencySymbol: '$' },
    { name: 'Dominican Republic', currency: 'DOP', phonePrefix: '+1', currencySymbol: '$' },
    { name: 'East Timor', currency: 'USD', phonePrefix: '+670', currencySymbol: '$' },
    { name: 'Ecuador', currency: 'USD', phonePrefix: '+593', currencySymbol: '$' },
    { name: 'Egypt', currency: 'EGP', phonePrefix: '+20', currencySymbol: '£' },
    { name: 'El Salvador', currency: 'USD', phonePrefix: '+503', currencySymbol: '$' },
    { name: 'Equatorial Guinea', currency: 'XAF', phonePrefix: '+240', currencySymbol: 'FCFA' },
    { name: 'Eritrea', currency: 'ERN', phonePrefix: '+291', currencySymbol: 'Nfk' },
    { name: 'Estonia', currency: 'EUR', phonePrefix: '+372', currencySymbol: '€' },
    { name: 'Ethiopia', currency: 'ETB', phonePrefix: '+251', currencySymbol: 'Br' },
    { name: 'Fiji', currency: 'FJD', phonePrefix: '+679', currencySymbol: '$' },
    { name: 'Finland', currency: 'EUR', phonePrefix: '+358', currencySymbol: '€' },
    { name: 'France', currency: 'EUR', phonePrefix: '+33', currencySymbol: '€' },
    { name: 'Gabon', currency: 'XAF', phonePrefix: '+241', currencySymbol: 'FCFA' },
    { name: 'Gambia', currency: 'GMD', phonePrefix: '+220', currencySymbol: 'D' },
    { name: 'Georgia', currency: 'GEL', phonePrefix: '+995', currencySymbol: '₾' },
    { name: 'Germany', currency: 'EUR', phonePrefix: '+49', currencySymbol: '€' },
    { name: 'Ghana', currency: 'GHS', phonePrefix: '+233', currencySymbol: '₵' },
    { name: 'Greece', currency: 'EUR', phonePrefix: '+30', currencySymbol: '€' },
    { name: 'Grenada', currency: 'XCD', phonePrefix: '+1', currencySymbol: '$' },
    { name: 'Guatemala', currency: 'GTQ', phonePrefix: '+502', currencySymbol: 'Q' },
    { name: 'Guinea', currency: 'GNF', phonePrefix: '+224', currencySymbol: 'FG' },
    { name: 'Guinea-Bissau', currency: 'XOF', phonePrefix: '+245', currencySymbol: 'CFA' },
    { name: 'Guyana', currency: 'GYD', phonePrefix: '+592', currencySymbol: '$' },
    { name: 'Haiti', currency: 'HTG', phonePrefix: '+509', currencySymbol: 'G' },
    { name: 'Honduras', currency: 'HNL', phonePrefix: '+504', currencySymbol: 'L' },
    { name: 'Hungary', currency: 'HUF', phonePrefix: '+36', currencySymbol: 'Ft' },
    { name: 'Iceland', currency: 'ISK', phonePrefix: '+354', currencySymbol: 'kr' },
    { name: 'India', currency: 'INR', phonePrefix: '+91', currencySymbol: '₹' },
    { name: 'Indonesia', currency: 'IDR', phonePrefix: '+62', currencySymbol: 'Rp' },
    { name: 'Iran', currency: 'IRR', phonePrefix: '+98', currencySymbol: '﷼' },
    { name: 'Iraq', currency: 'IQD', phonePrefix: '+964', currencySymbol: 'ع.د' },
    { name: 'Ireland {Republic}', currency: 'EUR', phonePrefix: '+353', currencySymbol: '€' },
    { name: 'Israel', currency: 'ILS', phonePrefix: '+972', currencySymbol: '₪' },
    { name: 'Italy', currency: 'EUR', phonePrefix: '+39', currencySymbol: '€' },
    { name: 'Ivory Coast', currency: 'XOF', phonePrefix: '+225', currencySymbol: 'CFA' },
    { name: 'Jamaica', currency: 'JMD', phonePrefix: '+1', currencySymbol: '$' },
    { name: 'Japan', currency: 'JPY', phonePrefix: '+81', currencySymbol: '¥' },
    { name: 'Jordan', currency: 'JOD', phonePrefix: '+962', currencySymbol: 'د.ا' },
    { name: 'Kazakhstan', currency: 'KZT', phonePrefix: '+7', currencySymbol: '₸' },
    { name: 'Kenya', currency: 'KES', phonePrefix: '+254', currencySymbol: 'KSh' },
    { name: 'Kiribati', currency: 'AUD', phonePrefix: '+686', currencySymbol: '$' },
    { name: 'Korea North', currency: 'KPW', phonePrefix: '+850', currencySymbol: '₩' },
    { name: 'Korea South', currency: 'KRW', phonePrefix: '+82', currencySymbol: '₩' },
    { name: 'Kosovo', currency: 'EUR', phonePrefix: '+383', currencySymbol: '€' },
    { name: 'Kuwait', currency: 'KWD', phonePrefix: '+965', currencySymbol: 'د.ك' },
    { name: 'Kyrgyzstan', currency: 'KGS', phonePrefix: '+996', currencySymbol: 'с' },
    { name: 'Laos', currency: 'LAK', phonePrefix: '+856', currencySymbol: '₭' },
    { name: 'Latvia', currency: 'EUR', phonePrefix: '+371', currencySymbol: '€' },
    { name: 'Lebanon', currency: 'LBP', phonePrefix: '+961', currencySymbol: 'ل.ل' },
    { name: 'Lesotho', currency: 'LSL', phonePrefix: '+266', currencySymbol: 'L' },
    { name: 'Liberia', currency: 'LRD', phonePrefix: '+231', currencySymbol: '$' },
    { name: 'Libya', currency: 'LYD', phonePrefix: '+218', currencySymbol: 'ل.د' },
    { name: 'Liechtenstein', currency: 'CHF', phonePrefix: '+423', currencySymbol: 'CHF' },
    { name: 'Lithuania', currency: 'EUR', phonePrefix: '+370', currencySymbol: '€' },
    { name: 'Luxembourg', currency: 'EUR', phonePrefix: '+352', currencySymbol: '€' },
    { name: 'Macedonia', currency: 'MKD', phonePrefix: '+389', currencySymbol: 'ден' },
    { name: 'Madagascar', currency: 'MGA', phonePrefix: '+261', currencySymbol: 'Ar' },
    { name: 'Malawi', currency: 'MWK', phonePrefix: '+265', currencySymbol: 'MK' },
    { name: 'Malaysia', currency: 'MYR', phonePrefix: '+60', currencySymbol: 'RM' },
    { name: 'Maldives', currency: 'MVR', phonePrefix: '+960', currencySymbol: 'Rf' },
    { name: 'Mali', currency: 'XOF', phonePrefix: '+223', currencySymbol: 'CFA' },
    { name: 'Malta', currency: 'EUR', phonePrefix: '+356', currencySymbol: '€' },
    { name: 'Marshall Islands', currency: 'USD', phonePrefix: '+692', currencySymbol: '$' },
    { name: 'Mauritania', currency: 'MRU', phonePrefix: '+222', currencySymbol: 'UM' },
    { name: 'Mauritius', currency: 'MUR', phonePrefix: '+230', currencySymbol: '₨' },
    { name: 'Mexico', currency: 'MXN', phonePrefix: '+52', currencySymbol: '$' },
    { name: 'Micronesia', currency: 'USD', phonePrefix: '+691', currencySymbol: '$' },
    { name: 'Moldova', currency: 'MDL', phonePrefix: '+373', currencySymbol: 'L' },
    { name: 'Monaco', currency: 'EUR', phonePrefix: '+377', currencySymbol: '€' },
    { name: 'Mongolia', currency: 'MNT', phonePrefix: '+976', currencySymbol: '₮' },
    { name: 'Montenegro', currency: 'EUR', phonePrefix: '+382', currencySymbol: '€' },
    { name: 'Morocco', currency: 'MAD', phonePrefix: '+212', currencySymbol: 'د.م.' },
    { name: 'Mozambique', currency: 'MZN', phonePrefix: '+258', currencySymbol: 'MT' },
    { name: 'Myanmar', currency: 'MMK', phonePrefix: '+95', currencySymbol: 'K' },
    { name: 'Namibia', currency: 'NAD', phonePrefix: '+264', currencySymbol: '$' },
    { name: 'Nauru', currency: 'AUD', phonePrefix: '+674', currencySymbol: '$' },
    { name: 'Nepal', currency: 'NPR', phonePrefix: '+977', currencySymbol: 'रू' },
    { name: 'Netherlands', currency: 'EUR', phonePrefix: '+31', currencySymbol: '€' },
    { name: 'New Zealand', currency: 'NZD', phonePrefix: '+64', currencySymbol: '$' },
    { name: 'Nicaragua', currency: 'NIO', phonePrefix: '+505', currencySymbol: 'C$' },
    { name: 'Niger', currency: 'XOF', phonePrefix: '+227', currencySymbol: 'CFA' },
    { name: 'Nigeria', currency: 'NGN', phonePrefix: '+234', currencySymbol: '₦' },
    { name: 'Norway', currency: 'NOK', phonePrefix: '+47', currencySymbol: 'kr' },
    { name: 'Oman', currency: 'OMR', phonePrefix: '+968', currencySymbol: 'ر.ع.' },
    { name: 'Pakistan', currency: 'PKR', phonePrefix: '+92', currencySymbol: '₨' },
    { name: 'Palau', currency: 'USD', phonePrefix: '+680', currencySymbol: '$' },
    { name: 'Panama', currency: 'PAB', phonePrefix: '+507', currencySymbol: 'B/.' },
    { name: 'Papua New Guinea', currency: 'PGK', phonePrefix: '+675', currencySymbol: 'K' },
    { name: 'Paraguay', currency: 'PYG', phonePrefix: '+595', currencySymbol: '₲' },
    { name: 'Peru', currency: 'PEN', phonePrefix: '+51', currencySymbol: 'S/' },
    { name: 'Philippines', currency: 'PHP', phonePrefix: '+63', currencySymbol: '₱' },
    { name: 'Poland', currency: 'PLN', phonePrefix: '+48', currencySymbol: 'zł' },
    { name: 'Portugal', currency: 'EUR', phonePrefix: '+351', currencySymbol: '€' },
    { name: 'Qatar', currency: 'QAR', phonePrefix: '+974', currencySymbol: 'ر.ق' },
    { name: 'Romania', currency: 'RON', phonePrefix: '+40', currencySymbol: 'lei' },
    { name: 'Russian Federation', currency: 'RUB', phonePrefix: '+7', currencySymbol: '₽' },
    { name: 'Rwanda', currency: 'RWF', phonePrefix: '+250', currencySymbol: 'RF' },
    { name: 'St Kitts & Nevis', currency: 'XCD', phonePrefix: '+1', currencySymbol: '$' },
    { name: 'St Lucia', currency: 'XCD', phonePrefix: '+1', currencySymbol: '$' },
    { name: 'Saint Vincent & the Grenadines', currency: 'XCD', phonePrefix: '+1', currencySymbol: '$' },
    { name: 'Samoa', currency: 'WST', phonePrefix: '+685', currencySymbol: 'T' },
    { name: 'San Marino', currency: 'EUR', phonePrefix: '+378', currencySymbol: '€' },
    { name: 'Sao Tome & Principe', currency: 'STD', phonePrefix: '+239', currencySymbol: 'Db' },
    { name: 'Saudi Arabia', currency: 'SAR', phonePrefix: '+966', currencySymbol: 'ر.س' },
    { name: 'Senegal', currency: 'XOF', phonePrefix: '+221', currencySymbol: 'CFA' },
    { name: 'Serbia', currency: 'RSD', phonePrefix: '+381', currencySymbol: 'din' },
    { name: 'Seychelles', currency: 'SCR', phonePrefix: '+248', currencySymbol: '₨' },
    { name: 'Sierra Leone', currency: 'SLL', phonePrefix: '+232', currencySymbol: 'Le' },
    { name: 'Singapore', currency: 'SGD', phonePrefix: '+65', currencySymbol: '$' },
    { name: 'Slovakia', currency: 'EUR', phonePrefix: '+421', currencySymbol: '€' },
    { name: 'Slovenia', currency: 'EUR', phonePrefix: '+386', currencySymbol: '€' },
    { name: 'Solomon Islands', currency: 'SBD', phonePrefix: '+677', currencySymbol: '$' },
    { name: 'Somalia', currency: 'SOS', phonePrefix: '+252', currencySymbol: 'S' },
    { name: 'South Africa', currency: 'ZAR', phonePrefix: '+27', currencySymbol: 'R' },
    { name: 'South Sudan', currency: 'SSP', phonePrefix: '+211', currencySymbol: '£' },
    { name: 'Spain', currency: 'EUR', phonePrefix: '+34', currencySymbol: '€' },
    { name: 'Sri Lanka', currency: 'LKR', phonePrefix: '+94', currencySymbol: '₨' },
    { name: 'Sudan', currency: 'SDG', phonePrefix: '+249', currencySymbol: 'ج.س.' },
    { name: 'Suriname', currency: 'SRD', phonePrefix: '+597', currencySymbol: '$' },
    { name: 'Swaziland', currency: 'SZL', phonePrefix: '+268', currencySymbol: 'E' },
    { name: 'Sweden', currency: 'SEK', phonePrefix: '+46', currencySymbol: 'kr' },
    { name: 'Switzerland', currency: 'CHF', phonePrefix: '+41', currencySymbol: 'CHF' },
    { name: 'Syria', currency: 'SYP', phonePrefix: '+963', currencySymbol: '£' },
    { name: 'Taiwan', currency: 'TWD', phonePrefix: '+886', currencySymbol: 'NT$' },
    { name: 'Tajikistan', currency: 'TJS', phonePrefix: '+992', currencySymbol: 'ЅМ' },
    { name: 'Tanzania', currency: 'TZS', phonePrefix: '+255', currencySymbol: 'Sh' },
    { name: 'Thailand', currency: 'THB', phonePrefix: '+66', currencySymbol: '฿' },
    { name: 'Togo', currency: 'XOF', phonePrefix: '+228', currencySymbol: 'CFA' },
    { name: 'Tonga', currency: 'TOP', phonePrefix: '+676', currencySymbol: 'T$' },
    { name: 'Trinidad & Tobago', currency: 'TTD', phonePrefix: '+1', currencySymbol: '$' },
    { name: 'Tunisia', currency: 'TND', phonePrefix: '+216', currencySymbol: 'د.ت' },
    { name: 'Turkey', currency: 'TRY', phonePrefix: '+90', currencySymbol: '₺' },
    { name: 'Turkmenistan', currency: 'TMT', phonePrefix: '+993', currencySymbol: 'T' },
    { name: 'Tuvalu', currency: 'AUD', phonePrefix: '+688', currencySymbol: '$' },
    { name: 'Uganda', currency: 'UGX', phonePrefix: '+256', currencySymbol: 'USh' },
    { name: 'Ukraine', currency: 'UAH', phonePrefix: '+380', currencySymbol: '₴' },
    { name: 'United Arab Emirates', currency: 'AED', phonePrefix: '+971', currencySymbol: 'د.إ' },
    { name: 'United Kingdom', currency: 'GBP', phonePrefix: '+44', currencySymbol: '£' },
    { name: 'United States', currency: 'USD', phonePrefix: '+1', currencySymbol: '$' },
    { name: 'Uruguay', currency: 'UYU', phonePrefix: '+598', currencySymbol: '$U' },
    { name: 'Uzbekistan', currency: 'UZS', phonePrefix: '+998', currencySymbol: 'лв' },
    { name: 'Vanuatu', currency: 'VUV', phonePrefix: '+678', currencySymbol: 'VT' },
    { name: 'Vatican City', currency: 'EUR', phonePrefix: '+379', currencySymbol: '€' },
    { name: 'Venezuela', currency: 'VES', phonePrefix: '+58', currencySymbol: 'Bs.S.' },
    { name: 'Vietnam', currency: 'VND', phonePrefix: '+84', currencySymbol: '₫' },
    { name: 'Yemen', currency: 'YER', phonePrefix: '+967', currencySymbol: '﷼' },
    { name: 'Zambia', currency: 'ZMW', phonePrefix: '+260', currencySymbol: 'ZK' },
    { name: 'Zimbabwe', currency: 'ZWL', phonePrefix: '+263', currencySymbol: 'Z$' }
];
